/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F4XX.h"
#include "STM32FXX_GPIO_DRIVER.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    GPIO_HANDLE_t GpioLed;
    GpioLed.pGPIOx = GPIOD;
    GpioLed.PIN_CONGFIG.GPIO_PinNumber = GPIO_Pin_Number_15;
    GpioLed.PIN_CONGFIG.GPIO_PinMode = GPIO_Pin_Mode_Out;
    GpioLed.PIN_CONGFIG.GPIO_PinSpeed = GPIO_Pin_Speed_Fast	;
    GpioLed.PIN_CONGFIG.GPIO_PinOPType = GPIO_Pin_PP	;
    GpioLed.PIN_CONGFIG.GPIO_PinPuPdControl = GPIO_Pin_PU;

}
